"""
Intervention handling for workflow constraint violations.

Simplified: messages come directly from constraint violations (generated by
the compiler from rule text). No separate interventions template map.
"""

import logging

from opensentinel.core.intervention.strategies import (
    StrategyConfig,
    StrategyType,
)
from opensentinel.policy.engines.fsm.workflow.constraints import ConstraintViolation

logger = logging.getLogger(__name__)


class InterventionHandler:
    """
    Builds StrategyConfig from constraint violations.

    Messages are stored on constraint objects (generated by the compiler
    from rule text). This handler wraps them in StrategyConfig for
    the interceptor layer.
    """

    def __init__(
        self,
        default_strategy: StrategyType = StrategyType.SYSTEM_PROMPT_APPEND,
        max_intervention_attempts: int = 3,
    ) -> None:
        self.default_strategy = default_strategy
        self.max_intervention_attempts = max_intervention_attempts

    def get_config_for_violation(
        self, violation: ConstraintViolation
    ) -> StrategyConfig:
        """Build an StrategyConfig from a constraint violation."""
        return StrategyConfig(
            strategy_type=self.default_strategy,
            message_template=violation.message,
            max_applications=self.max_intervention_attempts,
        )

    def get_message(self, violation: ConstraintViolation) -> str | None:
        """Get the intervention message from a violation."""
        return violation.message or None
